parameters:
    itkg_api_extra.subscriber.webservice_wrapper.class: Itkg\ApiExtraBundle\EventSubscriber\WebserviceWrapperSubscriber
    itkg_api_extra.subscriber.serialization_listener.class: Itkg\ApiExtraBundle\EventSubscriber\SerializationExceptionSubscriber
    itkg_api_extra.subscriber.unknown_exception_listener.class: Itkg\ApiExtraBundle\EventSubscriber\UnknownExceptionSubscriber
    itkg_api_extra.subscriber.response_cacher.class: Itkg\ApiExtraBundle\EventSubscriber\ResponseCacherSubscriber
    itkg_api_extra.cacher.response.class: Itkg\ApiExtraBundle\Cacher\ResponseCacher
    itkg_api_extra.subscriber.request_cache_reader.class: Itkg\ApiExtraBundle\EventSubscriber\RequestCacheReaderSubscriber

services:
    itkg_api_extra.subscriber.webservice_wrapper:
        class: %itkg_api_extra.subscriber.webservice_wrapper.class%
        arguments:
            - @annotation_reader
            - @controller_resolver
        tags:
            - { name: kernel.event_subscriber }
    itkg_api_extra.subscriber.serialization_listener:
        class: %itkg_api_extra.subscriber.serialization_listener.class%
        arguments:
            - @annotation_reader
            - @controller_resolver
        tags:
            - { name: kernel.event_subscriber }

    itkg_api_extra.subscriber.unknown_exception_listener:
        class: %itkg_api_extra.subscriber.unknown_exception_listener.class%
        arguments:
            - @annotation_reader
            - @controller_resolver
            - %kernel.debug%
        tags:
            - { name: kernel.event_subscriber }

    itkg_api_extra.subscriber.response_cacher:
        class: %itkg_api_extra.subscriber.response_cacher.class%
        arguments:
            - @security.token_storage
            - @security.authorization_checker
            - @itkg_api_extra.cacher.response
            - %api.route.cached%
        tags:
            - { name: kernel.event_subscriber }

    itkg_api_extra.subscriber.request_cache_reader:
            class: %itkg_api_extra.subscriber.request_cache_reader.class%
            arguments:
                - @annotation_reader
                - @controller_resolver
                - @itkg_api_extra.cacher.response
                - %api.route.cached%
            tags:
                - { name: kernel.event_subscriber }

    itkg_api_extra.cacher.response:
        class: %itkg_api_extra.cacher.response.class%
        arguments:
            - @itkg.cache.adapter

    itkg.cache.adapter:
        class: Itkg\Core\Cache\Adapter\Redis
        arguments:
            - default:
                host: 172.17.0.2
                port: 6379
